name: CI

on: [push, pull_request]

jobs:
  ubuntu-gcc-20:
    name: Ubuntu (gcc-${{ matrix.gcc }})
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        gcc: ["7", "8"]
    steps:
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.gcc }}
          platform: x64
      - uses: actions/checkout@v3
      - name: Build linux
        run: |
          gcc --version
          cd linux
          ./b configure
          ./b build
      - name: Build linux_dpdk
        run: |
          cd linux_dpdk
          ./b configure
          ./b build

  ubuntu-gcc-22:
    name: Ubuntu (gcc)
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        gcc: ["9", "10", "11", "12", "13"]
    steps:
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.gcc }}
          platform: x64
      - uses: actions/checkout@v3
      - name: Build linux
        run: |
          gcc --version
          cd linux
          ./b configure
          ./b build
      - name: Build linux_dpdk
        run: |
          cd linux_dpdk
          ./b configure
          ./b build

  ubuntu-clang:
    name: Ubuntu (clang-${{ matrix.clang }})
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # clang: ["6.0", "7", "8", "9", "10", "11", "12", "13", "14", "15"]
        clang: ["9", "10", "11", "12", "13", "14", "15"]
    steps:
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: ${{ matrix.clang }}
          platform: x64
      - uses: actions/checkout@v3
      # - name: Build linux
      #   env:
      #     CC: clang
      #     CXX: clang++
      #   run: |
      #     clang --version
      #     cd linux
      #     ./b configure
      #     ./b build
      - name: Build linux_dpdk
        env:
          CC: clang
          CXX: clang++
        run: |
          cd linux_dpdk
          ./b configure
          ./b build

